//! Worked example: FIDO Metadata Service (MDS) integration.
//!
//! A valid attestation signature only proves a credential was generated by
//! *some* FIDO-conformant authenticator — not that the specific hardware
//! model is still trustworthy. The FIDO Alliance publishes a signed BLOB
//! (FIDO MDS3 §3.2/§3.3) listing known-compromised authenticator models by
//! AAGUID. `metadata::verify_and_parse_mds_blob` verifies that BLOB's JWS
//! signature and `x5c` chain and parses it into per-AAGUID status data;
//! `RelyingParty::authenticator_metadata` wires the result into
//! `verify_registration` so a registration from a revoked or key-compromised
//! model is rejected before it's ever stored.
//!
//! This example builds a synthetic, self-signed MDS BLOB rather than fetching
//! the real one from <https://mds3.fidoalliance.org/>:
//!
//! 1. **Caden is deliberately stateless and I/O-free** (see "Stateless
//!    RelyingParty" in `CLAUDE.md`) — the library never performs the HTTP GET
//!    itself, by design, so an example living inside this crate shouldn't
//!    either. In production, fetch the BLOB on a schedule (FIDO Alliance
//!    rotates it periodically) with whatever HTTP client your application
//!    already uses, and verify it against the real FIDO Alliance root CA.
//! 2. **Determinism.** This example exists to show a registration get
//!    *rejected*, which means pinning a specific AAGUID to a specific status.
//!    The real BLOB's contents change over time, and no fixed AAGUID is
//!    guaranteed to stay `REVOKED` forever, so a live fetch would make this
//!    example flaky in exactly the scenario it's meant to demonstrate.
//!    `examples/demo.rs` and `examples/generate_vectors.rs` follow the same
//!    fixture-over-fetch precedent for the same reason.
//!
//! Run with: `cargo run --example mds_metadata`
//!
//! The example walks through:
//! 1. Building a synthetic MDS BLOB — ES256-signed, 2-certificate `x5c`
//!    chain, two AAGUID entries.
//! 2. Verifying it with `metadata::verify_and_parse_mds_blob` and inspecting
//!    the parsed per-AAGUID status map.
//! 3. Wiring the parsed statuses into a `RelyingParty` via
//!    `.authenticator_metadata(...)`.
//! 4. A clean registration from an authenticator model with no compromised
//!    status — accepted.
//! 5. A registration from an authenticator model marked `REVOKED` — rejected
//!    with `WebAuthnError::AuthenticatorStatusUntrusted`.

use anyhow::{Context, Result};
use base64::{
    engine::general_purpose::{STANDARD, URL_SAFE_NO_PAD},
    Engine as _,
};
use ciborium::value::Value;
use ring::rand::SystemRandom;
use ring::signature::{EcdsaKeyPair, KeyPair, ECDSA_P256_SHA256_ASN1_SIGNING};

use webauthn::{
    verify_and_parse_mds_blob, AuthenticatorAttestationResponse, Challenge, RelyingParty,
    WebAuthnError,
};

const RP_ID: &str = "localhost";
const ORIGIN: &str = "http://localhost";
const USER_ID: &[u8] = b"demo-user-001";

// Two simulated authenticator models, distinguished by AAGUID. The MDS BLOB
// built below marks TRUSTED_AAGUID as FIDO-certified and REVOKED_AAGUID as
// REVOKED.
const TRUSTED_AAGUID_STR: &str = "11111111-1111-1111-1111-111111111111";
const TRUSTED_AAGUID: [u8; 16] = [0x11; 16];
const REVOKED_AAGUID_STR: &str = "22222222-2222-2222-2222-222222222222";
const REVOKED_AAGUID: [u8; 16] = [0x22; 16];

fn main() -> Result<()> {
    println!("🔑 Caden MDS metadata demo");
    println!("─────────────────────────────────────");

    let rng = SystemRandom::new();

    // ── Step 1: Build a synthetic MDS BLOB ────────────────────────────────────
    println!("\n[Build synthetic MDS BLOB]");

    let (root_key, root_cert, root_der) = make_mds_root()?;
    let (leaf_key, leaf_der) = make_mds_signing_leaf(&root_cert, &root_key)?;

    let payload = serde_json::json!({
        "entries": [
            {
                "aaguid": TRUSTED_AAGUID_STR,
                "statusReports": [{ "status": "FIDO_CERTIFIED_L2" }],
            },
            {
                "aaguid": REVOKED_AAGUID_STR,
                "statusReports": [{ "status": "REVOKED" }],
            },
        ]
    })
    .to_string();

    let blob = build_mds_blob(&leaf_key, &[leaf_der, root_der.clone()], &payload)?;
    println!(
        "  BLOB built: {} bytes, ES256-signed, 2-certificate x5c chain",
        blob.len()
    );

    // ── Step 2: Verify the BLOB and parse per-AAGUID status ───────────────────
    println!("\n[Verify MDS BLOB — metadata::verify_and_parse_mds_blob]");

    let statuses =
        verify_and_parse_mds_blob(&blob, &root_der).context("MDS BLOB verification failed")?;

    println!("  JWS signature verified (ES256, x5c[0] leaf key)");
    println!("  x5c chain order verified, root matches the supplied trust_root");
    println!("  Parsed {} AAGUID entries:", statuses.len());
    for (aaguid, s) in &statuses {
        println!("    {} → {s:?}", hex(aaguid));
    }

    // ── Step 3: Wire the parsed statuses into a RelyingParty ──────────────────
    let rp = RelyingParty::new(RP_ID, ORIGIN, "Caden MDS Demo").authenticator_metadata(statuses);

    // ── Step 4: Registration from a trusted authenticator model ───────────────
    println!(
        "\n[Registration — trusted authenticator model, AAGUID {}]",
        hex(&TRUSTED_AAGUID)
    );

    let (trusted_challenge, trusted_response) = build_attestation_response(&rng, &TRUSTED_AAGUID)?;
    let trusted_result = rp
        .verify_registration(&trusted_challenge, &trusted_response, USER_ID)
        .context("registration from the trusted authenticator model should have succeeded")?;

    println!("  AAGUID has no compromised status in authenticator_metadata — allowed through");
    println!(
        "  Registration accepted, credential ID: {}",
        hex(&trusted_result.credential.id)
    );

    // ── Step 5: Registration from a revoked authenticator model ───────────────
    println!(
        "\n[Registration — revoked authenticator model, AAGUID {}]",
        hex(&REVOKED_AAGUID)
    );

    let (revoked_challenge, revoked_response) = build_attestation_response(&rng, &REVOKED_AAGUID)?;
    match rp.verify_registration(&revoked_challenge, &revoked_response, USER_ID) {
        Err(WebAuthnError::AuthenticatorStatusUntrusted(status)) => {
            println!("  AAGUID is marked {status} in authenticator_metadata");
            println!("  Registration correctly rejected: AuthenticatorStatusUntrusted({status:?})");
        }
        Ok(_) => {
            panic!("BUG: registration from a REVOKED-status AAGUID should have been rejected!")
        }
        Err(e) => return Err(e.into()),
    }

    println!("\n─────────────────────────────────────");
    println!("All checks passed.");
    Ok(())
}

// ─── MDS BLOB construction (synthetic — see module docs for why) ──────────────

/// Build a self-signed CA certificate — stands in for the FIDO Alliance MDS
/// root CA.
fn make_mds_root() -> Result<(rcgen::KeyPair, rcgen::Certificate, Vec<u8>)> {
    let key = rcgen::KeyPair::generate()
        .map_err(|e| anyhow::anyhow!("failed to generate MDS root key: {e}"))?;
    let mut params = rcgen::CertificateParams::default();
    params.is_ca = rcgen::IsCa::Ca(rcgen::BasicConstraints::Unconstrained);
    let cert = params
        .self_signed(&key)
        .map_err(|e| anyhow::anyhow!("failed to self-sign MDS root cert: {e}"))?;
    let der = cert.der().to_vec();
    Ok((key, cert, der))
}

/// Build a leaf certificate signed by the given issuer — stands in for the
/// MDS BLOB signer certificate (`x5c[0]`).
fn make_mds_signing_leaf(
    issuer_cert: &rcgen::Certificate,
    issuer_key: &rcgen::KeyPair,
) -> Result<(rcgen::KeyPair, Vec<u8>)> {
    let leaf_key = rcgen::KeyPair::generate()
        .map_err(|e| anyhow::anyhow!("failed to generate MDS leaf key: {e}"))?;
    let der = rcgen::CertificateParams::default()
        .signed_by(&leaf_key, issuer_cert, issuer_key)
        .map_err(|e| anyhow::anyhow!("failed to sign MDS leaf cert: {e}"))?
        .der()
        .to_vec();
    Ok((leaf_key, der))
}

/// Sign `message` with `leaf_key`'s private key in JWS "fixed" (raw r||s)
/// ES256 encoding — RFC 7518 §3.4, what `verify_and_parse_mds_blob` expects.
fn jws_sign_es256(leaf_key: &rcgen::KeyPair, message: &[u8]) -> Result<Vec<u8>> {
    use ring::signature::ECDSA_P256_SHA256_FIXED_SIGNING;

    let rng = SystemRandom::new();
    let kp = EcdsaKeyPair::from_pkcs8(
        &ECDSA_P256_SHA256_FIXED_SIGNING,
        leaf_key.serialized_der(),
        &rng,
    )
    .map_err(|e| anyhow::anyhow!("failed to load MDS leaf signing key: {e}"))?;
    let sig = kp
        .sign(&rng, message)
        .map_err(|e| anyhow::anyhow!("MDS BLOB signing failed: {e}"))?;
    Ok(sig.as_ref().to_vec())
}

/// Build a complete, validly-signed MDS BLOB JWT (FIDO MDS3 §3.2) for the
/// given leaf signing key, leaf-first DER certificate chain, and payload
/// JSON (FIDO MDS3 §3.3).
fn build_mds_blob(
    leaf_key: &rcgen::KeyPair,
    chain_der: &[Vec<u8>],
    payload_json: &str,
) -> Result<String> {
    let x5c: Vec<String> = chain_der.iter().map(|c| STANDARD.encode(c)).collect();
    let header_json = serde_json::json!({
        "alg": "ES256",
        "typ": "JWT",
        "x5c": x5c,
    })
    .to_string();

    let header_b64 = URL_SAFE_NO_PAD.encode(header_json.as_bytes());
    let payload_b64 = URL_SAFE_NO_PAD.encode(payload_json.as_bytes());
    let signing_input = format!("{header_b64}.{payload_b64}");
    let sig = jws_sign_es256(leaf_key, signing_input.as_bytes())?;
    let sig_b64 = URL_SAFE_NO_PAD.encode(&sig);

    Ok(format!("{header_b64}.{payload_b64}.{sig_b64}"))
}

// ─── Authenticator simulation helpers ──────────────────────────────────────────

/// Simulate an ES256 authenticator registering a fresh credential with the
/// given AAGUID, and return the challenge and attestation response a browser
/// would hand back to the relying party.
fn build_attestation_response(
    rng: &SystemRandom,
    aaguid: &[u8; 16],
) -> Result<(Challenge, AuthenticatorAttestationResponse)> {
    let pkcs8 = EcdsaKeyPair::generate_pkcs8(&ECDSA_P256_SHA256_ASN1_SIGNING, rng)
        .map_err(|e| anyhow::anyhow!("failed to generate authenticator keypair: {e}"))?;
    let key_pair = EcdsaKeyPair::from_pkcs8(&ECDSA_P256_SHA256_ASN1_SIGNING, pkcs8.as_ref(), rng)
        .map_err(|e| anyhow::anyhow!("failed to load authenticator keypair: {e}"))?;
    let public_key_bytes = key_pair.public_key().as_ref().to_vec();

    let mut cred_id = vec![0u8; 16];
    ring::rand::SecureRandom::fill(rng, &mut cred_id)
        .map_err(|e| anyhow::anyhow!("failed to generate credential ID: {e}"))?;

    let challenge = Challenge::new().context("failed to generate challenge")?;
    let client_data_json = make_client_data_json_bytes("webauthn.create", &challenge.bytes, ORIGIN);
    let cose_key = encode_es256_cose_key(&public_key_bytes);
    let auth_data = make_authenticator_data(RP_ID, 0x41, aaguid, &cred_id, &cose_key);
    let attestation_object = make_attestation_object(&auth_data);

    Ok((
        challenge,
        AuthenticatorAttestationResponse {
            client_data_json,
            attestation_object,
        },
    ))
}

fn make_client_data_json_bytes(type_: &str, challenge: &[u8], origin: &str) -> Vec<u8> {
    let challenge_b64 = URL_SAFE_NO_PAD.encode(challenge);
    format!(
        r#"{{"type":"{type_}","challenge":"{challenge_b64}","origin":"{origin}","crossOrigin":false}}"#
    )
    .into_bytes()
}

/// Build a raw authenticator data buffer with attested credential data.
///
/// Layout: rpIdHash (32) | flags (1) | signCount (4) | aaguid (16) |
/// credentialIdLength (2) | credentialId | credentialPublicKey (CBOR)
fn make_authenticator_data(
    rp_id: &str,
    flags: u8,
    aaguid: &[u8; 16],
    cred_id: &[u8],
    cose_key_cbor: &[u8],
) -> Vec<u8> {
    let rp_id_hash = webauthn::crypto::sha256(rp_id.as_bytes());

    let mut out = Vec::new();
    out.extend_from_slice(&rp_id_hash);
    out.push(flags);
    out.extend_from_slice(&0u32.to_be_bytes()); // sign count 0 — initial registration
    out.extend_from_slice(aaguid);
    let id_len = cred_id.len() as u16;
    out.extend_from_slice(&id_len.to_be_bytes());
    out.extend_from_slice(cred_id);
    out.extend_from_slice(cose_key_cbor);

    out
}

fn encode_es256_cose_key(uncompressed_point: &[u8]) -> Vec<u8> {
    assert_eq!(
        uncompressed_point.len(),
        65,
        "expected 0x04 || x(32) || y(32)"
    );
    let x = uncompressed_point[1..33].to_vec();
    let y = uncompressed_point[33..65].to_vec();

    let cose_key = Value::Map(vec![
        (Value::Integer(1i64.into()), Value::Integer(2i64.into())), // kty: EC2
        (Value::Integer(3i64.into()), Value::Integer((-7i64).into())), // alg: ES256
        (Value::Integer((-1i64).into()), Value::Integer(1i64.into())), // crv: P-256
        (Value::Integer((-2i64).into()), Value::Bytes(x)),          // x
        (Value::Integer((-3i64).into()), Value::Bytes(y)),          // y
    ]);

    let mut buf = Vec::new();
    ciborium::into_writer(&cose_key, &mut buf).expect("CBOR encoding should not fail");
    buf
}

fn make_attestation_object(auth_data: &[u8]) -> Vec<u8> {
    let att_obj = Value::Map(vec![
        (
            Value::Text("fmt".to_string()),
            Value::Text("none".to_string()),
        ),
        (Value::Text("attStmt".to_string()), Value::Map(vec![])),
        (
            Value::Text("authData".to_string()),
            Value::Bytes(auth_data.to_vec()),
        ),
    ]);

    let mut buf = Vec::new();
    ciborium::into_writer(&att_obj, &mut buf).expect("CBOR encoding should not fail");
    buf
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
